name: dublin_stations
description: Which stations have space and which have bikes!

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+12'
  location: '^1.1.5'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
